name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version:
        - 1.21

    steps:
    - name: Setup Golang (${{ matrix.go-version }})
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.gp-version }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Unit tests
      run: make test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: rantanevich
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ github.token }}
